config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'home_page#index'
    resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    Book.create(book_params) 
    redirect_to root_path
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :author, :description)
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
    def index
        @books = Book.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/books/new.html.erb
 <%= simple_form_for @book do |f| %>
<div class="container">
    <hr>
    <div class="col row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <header class="card-header">

                    <%= f.error_notification %>
                    <h4 class="card-title mt-2">Add A New Book</h4>
                </header>
                <article class="card-body">
                    <form >
                    <br/>   
                        <div class="form-row">
                            <div class="col form-group">
                              <%= f.input :title,
                              required: true,
                              autofocus: true
                               %>
                            </div> <!-- form-group end.// -->
                        </div> <!-- form-row end.// -->
                        <div class="form-row">
                        </div> <!-- form-row.// -->
                        <div class="col form-group">
                           <%= f.input :author %>
                        </div> <!-- form-group end.// -->
                        <div class="form-row">
                        </div> <!-- form-row.// -->
                        <div class="col form-group">
                           <%= f.input :description %>
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <%= f.button :submit, "Add Book",  class:"btn my-btn-form " %>
                        </div> <!-- form-group// -->
                    </form>
                </article> <!-- card-body end .// -->
                
    <% end %>
</div> <!--container end.//-->
<br><br>

app/views/home_page/index.html.erb
<h1>Simple Web App to Display My Favorite Books</h1>
<p>Created using rails and hosted on github & heroku<p>
<%= link_to 'Add Book', new_book_path, class: 'badge badge-info' %>
<br/>



<% @books.each do |book| %>

<div class="card-group">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= book.title %></h5>
      <p class="card-text">
        Author: <%= book.author %>
        <br/>
        <%= book.description %>
      </p>
      <p class="card-text"><small class="text-muted"><%= book.created_at %></small></p>
    </div>
 

  <hr />
<% end %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>